# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de56a598a2890ee9a7aee6011dc83332b9ce8bd0349e75dbe24ad3bac3e035c1f7bb608de343a0a7797720341136736ae3295d7bb3d3226b7dad6cdc4a32e64e

test:
  secret_key_base: 97b1277672467fca210629bbca46c16e804c119b27cb9c9051ed3887ae88bb88407e810db76a5939cdc3e379d279f3ea828d553f24739a962c88154b6618dd16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
